title: Xing Huang
markdown: kramdown
url: "https://willxing.github.io"
baseurl: ""

# for atom feed
author:
  name: WillXing
  email: will.xing@outlook.com

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate_path: "/page:num/"

paginate: 5

collections_dir: all_collections
collections:
  category:
    output: true
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:title/

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
